import { assertEquals } from "@std/assert/equals";
import { getMap, mapToString, setAntinodes } from "./antenna.ts";

const example = `............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............`;

Deno.test(function exampleStringToMap() {
  assertEquals(mapToString(getMap(example)), example);
});

Deno.test(function exampleStringWithAntinodes() {
  const map = getMap(example);
  setAntinodes(map);
  assertEquals(
    mapToString(map),
    ``,
  );
});
